#!/usr/bin/env python
"""Generate doc/VV/vv_report.md from the verification cases' recorded results.

Reads vv_cases/*/metrics_*.json (full check details from the latest run) and
vv_cases/*/baselines.json (committed reference values, incl. the convergence
study) and writes a human-readable report.

Usage:
    preprocessor/.venv/bin/python tests/verification/make_report.py
"""

import json
from datetime import date
from pathlib import Path
import subprocess

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
REPORT = REPO / "doc" / "VV" / "vv_report.md"
CASES = ["straight_tube", "side_opening_tube", "y_bifurcation"]


def fmt(v):
    return f"{v:.4g}"


def main():
    try:
        rev = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=REPO,
                             capture_output=True, text=True).stdout.strip()
    except OSError:
        rev = "unknown"

    lines = [
        "# HemoFlow verification report",
        "",
        f"Generated by `tests/verification/make_report.py` on {date.today()} "
        f"(revision {rev}). Case definitions: `tests/verification/vv_cases/`; "
        "methodology: `vv_rationale.md`; plan: `vv_implementation_plan.md`.",
        "",
    ]

    for case in CASES:
        case_dir = HERE / "vv_cases" / case
        lines += [f"## {case}", ""]
        metric_files = sorted(case_dir.glob("metrics_*.json"))
        if not metric_files:
            lines += ["_No recorded run (run `run_case.py` first)._", ""]
            continue
        for mf in metric_files:
            tag = mf.stem.replace("metrics_", "").replace("_", " / ")
            data = json.loads(mf.read_text())
            lines += [f"### {tag}", "",
                      "| check | measured | expected | error | tolerance | status |",
                      "|---|---|---|---|---|---|"]
            for name, d in data.items():
                lines.append(
                    f"| {name} | {fmt(d['measured'])} | {fmt(d['expected'])} | "
                    f"{d['error']:.2%} | {d['tol']:.1%} | "
                    f"{'PASS' if d['passed'] else 'FAIL'} |")
            lines.append("")

        baselines_file = case_dir / "baselines.json"
        if baselines_file.exists():
            baselines = json.loads(baselines_file.read_text())
            conv = baselines.get("convergence")
            if conv:
                lines += ["### Grid convergence (dimensionless resistance K, exact = 1)", "",
                          "| dx [mm] | K |", "|---|---|"]
                for dx, k in zip(conv["dx_mm"], conv["K"]):
                    lines.append(f"| {dx} | {fmt(k)} |")
                lines += ["",
                          f"Observed order of convergence: "
                          f"**p = {conv['observed_order']:.2f}**", ""]

    lines += [
        "## Notes",
        "",
        "- Tolerances are per-check and documented in each case's `check.py`,",
        "  including the physical reasoning for wide tolerances on weak oracles",
        "  (e.g. the resistance-network split ignores junction losses).",
        "- Recorded values double as regression baselines (drift alarm at 3 %).",
        "",
    ]
    REPORT.write_text("\n".join(lines))
    print(f"wrote {REPORT}")


if __name__ == "__main__":
    main()
